const HOLDS_BUTTON_COLOR = 'rgba(70,130,180,.8)';
const HOLDS_BUTTON_COLOR_LIGHT = 'rgba(70,130,180,.1)';
const ROUTE_BUTTON_COLOR = 'rgba(70,180,130,.8)';
const ROUTE_BUTTON_COLOR_LIGHT = 'rgba(70,180,130,.1)';
const PLACEHOLDER_COLOR = 'rgba(0,0,0,.3)';
const SCREEN_BACKGROUND_COLOR = 'rgba(194, 233, 251, .25)';
const HIGHLIGHT_COLOR = 'rgba(0,0,0,.1)';
const START_HOLD_COLOR = 'rgba(0,255,0,.6)';
const END_HOLD_COLOR = 'rgba(255,0,0,.6)';
const HOLD_COLOR = 'rgba(255,255,255,.6)';
const START_TOGGLE_COLOR = 'green';
const END_TOGGLE_COLOR = 'rgba(255,0,0,.8)'

export {
  // Colors
  HOLDS_BUTTON_COLOR,
  HOLDS_BUTTON_COLOR_LIGHT,
  ROUTE_BUTTON_COLOR_LIGHT,
  ROUTE_BUTTON_COLOR,
  PLACEHOLDER_COLOR,
  SCREEN_BACKGROUND_COLOR,
  HIGHLIGHT_COLOR,
  START_HOLD_COLOR,
  END_HOLD_COLOR,
  HOLD_COLOR,
  START_TOGGLE_COLOR,
  END_TOGGLE_COLOR,
  // Dimensions
};
